package verasync

import (
	"fmt"
	"sort"
	"strings"
)

// StatusCounts tallies entries by status.
type StatusCounts map[Status]int

// Counts returns the per-status tally over all entries.
func (m *Manifest) Counts() StatusCounts {
	c := StatusCounts{}
	for _, e := range m.Rules {
		c[e.Status]++
	}
	return c
}

// Report renders VERAPDF_COVERAGE.md: a coverage summary followed by the full
// rule list grouped by spec and clause.
func (m *Manifest) Report() string {
	m.sort()
	var b strings.Builder
	b.WriteString("# veraPDF coverage\n\n")
	b.WriteString("_Auto-generated by `cmd/verasync -report`. Do not edit by hand — ")
	b.WriteString("edit `internal/verasync/coverage.yaml` and regenerate._\n\n")
	if m.Source != "" {
		fmt.Fprintf(&b, "veraPDF profiles: `%s`\n\n", m.Source)
	}

	// Overall summary.
	total := len(m.Rules)
	c := m.Counts()
	fmt.Fprintf(&b, "**%d veraPDF rules** — ", total)
	b.WriteString(summaryLine(c, total))
	b.WriteString("\n\n")

	// Per-spec summary table.
	b.WriteString("| Spec | rules | covered | partial | todo | n/a | wontfix |\n")
	b.WriteString("|---|--:|--:|--:|--:|--:|--:|\n")
	for _, spec := range []string{"UA1", "UA2"} {
		sc := StatusCounts{}
		n := 0
		for _, e := range m.Rules {
			if s, _, _ := parseVera(e.Vera); s == spec {
				sc[e.Status]++
				n++
			}
		}
		if n == 0 {
			continue
		}
		fmt.Fprintf(&b, "| PDF/%s | %d | %d | %d | %d | %d | %d |\n",
			spec, n, sc[StatusCovered], sc[StatusPartial], sc[StatusTodo], sc[StatusNA], sc[StatusWontfix])
	}
	b.WriteString("\n")

	// Full listing, grouped by spec then clause.
	for _, spec := range []string{"UA1", "UA2"} {
		var entries []Entry
		for _, e := range m.Rules {
			if s, _, _ := parseVera(e.Vera); s == spec {
				entries = append(entries, e)
			}
		}
		if len(entries) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## PDF/%s\n\n", spec)
		b.WriteString("| Rule | status | checks | requirement |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, e := range entries {
			status := string(e.Status)
			if e.Gone {
				status += " ⚠gone"
			}
			checks := strings.Join(e.Checks, ", ")
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
				e.Vera, status, checks, mdEscape(truncate(e.Desc, 140)))
		}
		b.WriteString("\n")
	}

	// Open gaps, most actionable first.
	gaps := m.Gaps()
	if len(gaps) > 0 {
		fmt.Fprintf(&b, "## Open gaps (%d)\n\n", len(gaps))
		for _, e := range gaps {
			note := ""
			if e.Note != "" {
				note = " — " + e.Note
			}
			fmt.Fprintf(&b, "- `%s` (%s): %s%s\n", e.Vera, e.Object, mdEscape(truncate(e.Desc, 160)), mdEscape(note))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// Gaps returns entries still awaiting implementation (status todo or partial),
// in canonical order.
func (m *Manifest) Gaps() []Entry {
	var out []Entry
	for _, e := range m.Rules {
		if e.Status == StatusTodo || e.Status == StatusPartial {
			out = append(out, e)
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		si, ci, ti := parseVera(out[i].Vera)
		sj, cj, tj := parseVera(out[j].Vera)
		return lessVera(si, ci, ti, sj, cj, tj)
	})
	return out
}

func summaryLine(c StatusCounts, total int) string {
	if total == 0 {
		return "no rules"
	}
	covered := c[StatusCovered]
	pct := covered * 100 / total
	return fmt.Sprintf("%d covered (%d%%), %d partial, %d todo, %d n/a, %d wontfix",
		covered, pct, c[StatusPartial], c[StatusTodo], c[StatusNA], c[StatusWontfix])
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return strings.TrimSpace(s[:n]) + "…"
}

// mdEscape neutralizes the pipe character so descriptions don't break table
// columns.
func mdEscape(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
